name: LuckyEnchantment
version: '1.0.0'
main: com.voc2048.LuckyEnchantment
api-version: '1.21'
author: 'Vocaloid2048'
commands:
    lehelp:
        description: Main command for LuckyEnchantment plugin
        aliases:
          - luckyhelp